# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kt-fitz/human-ergodicObj

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kt-fitz/human-ergodicObj

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kt-fitz/human-ergodicObj/CMakeFiles /home/kt-fitz/human-ergodicObj/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kt-fitz/human-ergodicObj/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dklmda_di_image

# Build rule for target.
dklmda_di_image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dklmda_di_image
.PHONY : dklmda_di_image

# fast build rule for target.
dklmda_di_image/fast:
	$(MAKE) -f CMakeFiles/dklmda_di_image.dir/build.make CMakeFiles/dklmda_di_image.dir/build
.PHONY : dklmda_di_image/fast

#=============================================================================
# Target rules for targets named edgedetect

# Build rule for target.
edgedetect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edgedetect
.PHONY : edgedetect

# fast build rule for target.
edgedetect/fast:
	$(MAKE) -f CMakeFiles/edgedetect.dir/build.make CMakeFiles/edgedetect.dir/build
.PHONY : edgedetect/fast

#=============================================================================
# Target rules for targets named ergsac_cartpend

# Build rule for target.
ergsac_cartpend: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ergsac_cartpend
.PHONY : ergsac_cartpend

# fast build rule for target.
ergsac_cartpend/fast:
	$(MAKE) -f CMakeFiles/ergsac_cartpend.dir/build.make CMakeFiles/ergsac_cartpend.dir/build
.PHONY : ergsac_cartpend/fast

#=============================================================================
# Target rules for targets named cleanfiles

# Build rule for target.
cleanfiles: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cleanfiles
.PHONY : cleanfiles

# fast build rule for target.
cleanfiles/fast:
	$(MAKE) -f CMakeFiles/cleanfiles.dir/build.make CMakeFiles/cleanfiles.dir/build
.PHONY : cleanfiles/fast

#=============================================================================
# Target rules for targets named mda_cartpend

# Build rule for target.
mda_cartpend: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mda_cartpend
.PHONY : mda_cartpend

# fast build rule for target.
mda_cartpend/fast:
	$(MAKE) -f CMakeFiles/mda_cartpend.dir/build.make CMakeFiles/mda_cartpend.dir/build
.PHONY : mda_cartpend/fast

#=============================================================================
# Target rules for targets named sac_doubleint

# Build rule for target.
sac_doubleint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sac_doubleint
.PHONY : sac_doubleint

# fast build rule for target.
sac_doubleint/fast:
	$(MAKE) -f CMakeFiles/sac_doubleint.dir/build.make CMakeFiles/sac_doubleint.dir/build
.PHONY : sac_doubleint/fast

#=============================================================================
# Target rules for targets named ergsac_mda

# Build rule for target.
ergsac_mda: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ergsac_mda
.PHONY : ergsac_mda

# fast build rule for target.
ergsac_mda/fast:
	$(MAKE) -f CMakeFiles/ergsac_mda.dir/build.make CMakeFiles/ergsac_mda.dir/build
.PHONY : ergsac_mda/fast

#=============================================================================
# Target rules for targets named sac_cartpend

# Build rule for target.
sac_cartpend: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sac_cartpend
.PHONY : sac_cartpend

# fast build rule for target.
sac_cartpend/fast:
	$(MAKE) -f CMakeFiles/sac_cartpend.dir/build.make CMakeFiles/sac_cartpend.dir/build
.PHONY : sac_cartpend/fast

#=============================================================================
# Target rules for targets named mig_mda_cartpend

# Build rule for target.
mig_mda_cartpend: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mig_mda_cartpend
.PHONY : mig_mda_cartpend

# fast build rule for target.
mig_mda_cartpend/fast:
	$(MAKE) -f CMakeFiles/mig_mda_cartpend.dir/build.make CMakeFiles/mig_mda_cartpend.dir/build
.PHONY : mig_mda_cartpend/fast

#=============================================================================
# Target rules for targets named dklsac_di_image

# Build rule for target.
dklsac_di_image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dklsac_di_image
.PHONY : dklsac_di_image

# fast build rule for target.
dklsac_di_image/fast:
	$(MAKE) -f CMakeFiles/dklsac_di_image.dir/build.make CMakeFiles/dklsac_di_image.dir/build
.PHONY : dklsac_di_image/fast

#=============================================================================
# Target rules for targets named ergsac_doubleint

# Build rule for target.
ergsac_doubleint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ergsac_doubleint
.PHONY : ergsac_doubleint

# fast build rule for target.
ergsac_doubleint/fast:
	$(MAKE) -f CMakeFiles/ergsac_doubleint.dir/build.make CMakeFiles/ergsac_doubleint.dir/build
.PHONY : ergsac_doubleint/fast

#=============================================================================
# Target rules for targets named ergsac_dilincoln

# Build rule for target.
ergsac_dilincoln: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ergsac_dilincoln
.PHONY : ergsac_dilincoln

# fast build rule for target.
ergsac_dilincoln/fast:
	$(MAKE) -f CMakeFiles/ergsac_dilincoln.dir/build.make CMakeFiles/ergsac_dilincoln.dir/build
.PHONY : ergsac_dilincoln/fast

#=============================================================================
# Target rules for targets named dklmda_si_image

# Build rule for target.
dklmda_si_image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dklmda_si_image
.PHONY : dklmda_si_image

# fast build rule for target.
dklmda_si_image/fast:
	$(MAKE) -f CMakeFiles/dklmda_si_image.dir/build.make CMakeFiles/dklmda_si_image.dir/build
.PHONY : dklmda_si_image/fast

#=============================================================================
# Target rules for targets named dklsac_doubleint

# Build rule for target.
dklsac_doubleint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dklsac_doubleint
.PHONY : dklsac_doubleint

# fast build rule for target.
dklsac_doubleint/fast:
	$(MAKE) -f CMakeFiles/dklsac_doubleint.dir/build.make CMakeFiles/dklsac_doubleint.dir/build
.PHONY : dklsac_doubleint/fast

dklmda_di_image.o: dklmda_di_image.cpp.o

.PHONY : dklmda_di_image.o

# target to build an object file
dklmda_di_image.cpp.o:
	$(MAKE) -f CMakeFiles/dklmda_di_image.dir/build.make CMakeFiles/dklmda_di_image.dir/dklmda_di_image.cpp.o
.PHONY : dklmda_di_image.cpp.o

dklmda_di_image.i: dklmda_di_image.cpp.i

.PHONY : dklmda_di_image.i

# target to preprocess a source file
dklmda_di_image.cpp.i:
	$(MAKE) -f CMakeFiles/dklmda_di_image.dir/build.make CMakeFiles/dklmda_di_image.dir/dklmda_di_image.cpp.i
.PHONY : dklmda_di_image.cpp.i

dklmda_di_image.s: dklmda_di_image.cpp.s

.PHONY : dklmda_di_image.s

# target to generate assembly for a file
dklmda_di_image.cpp.s:
	$(MAKE) -f CMakeFiles/dklmda_di_image.dir/build.make CMakeFiles/dklmda_di_image.dir/dklmda_di_image.cpp.s
.PHONY : dklmda_di_image.cpp.s

dklmda_si_image.o: dklmda_si_image.cpp.o

.PHONY : dklmda_si_image.o

# target to build an object file
dklmda_si_image.cpp.o:
	$(MAKE) -f CMakeFiles/dklmda_si_image.dir/build.make CMakeFiles/dklmda_si_image.dir/dklmda_si_image.cpp.o
.PHONY : dklmda_si_image.cpp.o

dklmda_si_image.i: dklmda_si_image.cpp.i

.PHONY : dklmda_si_image.i

# target to preprocess a source file
dklmda_si_image.cpp.i:
	$(MAKE) -f CMakeFiles/dklmda_si_image.dir/build.make CMakeFiles/dklmda_si_image.dir/dklmda_si_image.cpp.i
.PHONY : dklmda_si_image.cpp.i

dklmda_si_image.s: dklmda_si_image.cpp.s

.PHONY : dklmda_si_image.s

# target to generate assembly for a file
dklmda_si_image.cpp.s:
	$(MAKE) -f CMakeFiles/dklmda_si_image.dir/build.make CMakeFiles/dklmda_si_image.dir/dklmda_si_image.cpp.s
.PHONY : dklmda_si_image.cpp.s

dklsac_di_image.o: dklsac_di_image.cpp.o

.PHONY : dklsac_di_image.o

# target to build an object file
dklsac_di_image.cpp.o:
	$(MAKE) -f CMakeFiles/dklsac_di_image.dir/build.make CMakeFiles/dklsac_di_image.dir/dklsac_di_image.cpp.o
.PHONY : dklsac_di_image.cpp.o

dklsac_di_image.i: dklsac_di_image.cpp.i

.PHONY : dklsac_di_image.i

# target to preprocess a source file
dklsac_di_image.cpp.i:
	$(MAKE) -f CMakeFiles/dklsac_di_image.dir/build.make CMakeFiles/dklsac_di_image.dir/dklsac_di_image.cpp.i
.PHONY : dklsac_di_image.cpp.i

dklsac_di_image.s: dklsac_di_image.cpp.s

.PHONY : dklsac_di_image.s

# target to generate assembly for a file
dklsac_di_image.cpp.s:
	$(MAKE) -f CMakeFiles/dklsac_di_image.dir/build.make CMakeFiles/dklsac_di_image.dir/dklsac_di_image.cpp.s
.PHONY : dklsac_di_image.cpp.s

dklsac_doubleint.o: dklsac_doubleint.cpp.o

.PHONY : dklsac_doubleint.o

# target to build an object file
dklsac_doubleint.cpp.o:
	$(MAKE) -f CMakeFiles/dklsac_doubleint.dir/build.make CMakeFiles/dklsac_doubleint.dir/dklsac_doubleint.cpp.o
.PHONY : dklsac_doubleint.cpp.o

dklsac_doubleint.i: dklsac_doubleint.cpp.i

.PHONY : dklsac_doubleint.i

# target to preprocess a source file
dklsac_doubleint.cpp.i:
	$(MAKE) -f CMakeFiles/dklsac_doubleint.dir/build.make CMakeFiles/dklsac_doubleint.dir/dklsac_doubleint.cpp.i
.PHONY : dklsac_doubleint.cpp.i

dklsac_doubleint.s: dklsac_doubleint.cpp.s

.PHONY : dklsac_doubleint.s

# target to generate assembly for a file
dklsac_doubleint.cpp.s:
	$(MAKE) -f CMakeFiles/dklsac_doubleint.dir/build.make CMakeFiles/dklsac_doubleint.dir/dklsac_doubleint.cpp.s
.PHONY : dklsac_doubleint.cpp.s

edgedetect.o: edgedetect.cpp.o

.PHONY : edgedetect.o

# target to build an object file
edgedetect.cpp.o:
	$(MAKE) -f CMakeFiles/edgedetect.dir/build.make CMakeFiles/edgedetect.dir/edgedetect.cpp.o
.PHONY : edgedetect.cpp.o

edgedetect.i: edgedetect.cpp.i

.PHONY : edgedetect.i

# target to preprocess a source file
edgedetect.cpp.i:
	$(MAKE) -f CMakeFiles/edgedetect.dir/build.make CMakeFiles/edgedetect.dir/edgedetect.cpp.i
.PHONY : edgedetect.cpp.i

edgedetect.s: edgedetect.cpp.s

.PHONY : edgedetect.s

# target to generate assembly for a file
edgedetect.cpp.s:
	$(MAKE) -f CMakeFiles/edgedetect.dir/build.make CMakeFiles/edgedetect.dir/edgedetect.cpp.s
.PHONY : edgedetect.cpp.s

ergsac_cartpend.o: ergsac_cartpend.cpp.o

.PHONY : ergsac_cartpend.o

# target to build an object file
ergsac_cartpend.cpp.o:
	$(MAKE) -f CMakeFiles/ergsac_cartpend.dir/build.make CMakeFiles/ergsac_cartpend.dir/ergsac_cartpend.cpp.o
.PHONY : ergsac_cartpend.cpp.o

ergsac_cartpend.i: ergsac_cartpend.cpp.i

.PHONY : ergsac_cartpend.i

# target to preprocess a source file
ergsac_cartpend.cpp.i:
	$(MAKE) -f CMakeFiles/ergsac_cartpend.dir/build.make CMakeFiles/ergsac_cartpend.dir/ergsac_cartpend.cpp.i
.PHONY : ergsac_cartpend.cpp.i

ergsac_cartpend.s: ergsac_cartpend.cpp.s

.PHONY : ergsac_cartpend.s

# target to generate assembly for a file
ergsac_cartpend.cpp.s:
	$(MAKE) -f CMakeFiles/ergsac_cartpend.dir/build.make CMakeFiles/ergsac_cartpend.dir/ergsac_cartpend.cpp.s
.PHONY : ergsac_cartpend.cpp.s

ergsac_dilincoln.o: ergsac_dilincoln.cpp.o

.PHONY : ergsac_dilincoln.o

# target to build an object file
ergsac_dilincoln.cpp.o:
	$(MAKE) -f CMakeFiles/ergsac_dilincoln.dir/build.make CMakeFiles/ergsac_dilincoln.dir/ergsac_dilincoln.cpp.o
.PHONY : ergsac_dilincoln.cpp.o

ergsac_dilincoln.i: ergsac_dilincoln.cpp.i

.PHONY : ergsac_dilincoln.i

# target to preprocess a source file
ergsac_dilincoln.cpp.i:
	$(MAKE) -f CMakeFiles/ergsac_dilincoln.dir/build.make CMakeFiles/ergsac_dilincoln.dir/ergsac_dilincoln.cpp.i
.PHONY : ergsac_dilincoln.cpp.i

ergsac_dilincoln.s: ergsac_dilincoln.cpp.s

.PHONY : ergsac_dilincoln.s

# target to generate assembly for a file
ergsac_dilincoln.cpp.s:
	$(MAKE) -f CMakeFiles/ergsac_dilincoln.dir/build.make CMakeFiles/ergsac_dilincoln.dir/ergsac_dilincoln.cpp.s
.PHONY : ergsac_dilincoln.cpp.s

ergsac_doubleint.o: ergsac_doubleint.cpp.o

.PHONY : ergsac_doubleint.o

# target to build an object file
ergsac_doubleint.cpp.o:
	$(MAKE) -f CMakeFiles/ergsac_doubleint.dir/build.make CMakeFiles/ergsac_doubleint.dir/ergsac_doubleint.cpp.o
.PHONY : ergsac_doubleint.cpp.o

ergsac_doubleint.i: ergsac_doubleint.cpp.i

.PHONY : ergsac_doubleint.i

# target to preprocess a source file
ergsac_doubleint.cpp.i:
	$(MAKE) -f CMakeFiles/ergsac_doubleint.dir/build.make CMakeFiles/ergsac_doubleint.dir/ergsac_doubleint.cpp.i
.PHONY : ergsac_doubleint.cpp.i

ergsac_doubleint.s: ergsac_doubleint.cpp.s

.PHONY : ergsac_doubleint.s

# target to generate assembly for a file
ergsac_doubleint.cpp.s:
	$(MAKE) -f CMakeFiles/ergsac_doubleint.dir/build.make CMakeFiles/ergsac_doubleint.dir/ergsac_doubleint.cpp.s
.PHONY : ergsac_doubleint.cpp.s

ergsac_mda.o: ergsac_mda.cpp.o

.PHONY : ergsac_mda.o

# target to build an object file
ergsac_mda.cpp.o:
	$(MAKE) -f CMakeFiles/ergsac_mda.dir/build.make CMakeFiles/ergsac_mda.dir/ergsac_mda.cpp.o
.PHONY : ergsac_mda.cpp.o

ergsac_mda.i: ergsac_mda.cpp.i

.PHONY : ergsac_mda.i

# target to preprocess a source file
ergsac_mda.cpp.i:
	$(MAKE) -f CMakeFiles/ergsac_mda.dir/build.make CMakeFiles/ergsac_mda.dir/ergsac_mda.cpp.i
.PHONY : ergsac_mda.cpp.i

ergsac_mda.s: ergsac_mda.cpp.s

.PHONY : ergsac_mda.s

# target to generate assembly for a file
ergsac_mda.cpp.s:
	$(MAKE) -f CMakeFiles/ergsac_mda.dir/build.make CMakeFiles/ergsac_mda.dir/ergsac_mda.cpp.s
.PHONY : ergsac_mda.cpp.s

filesplit.o: filesplit.cpp.o

.PHONY : filesplit.o

# target to build an object file
filesplit.cpp.o:
	$(MAKE) -f CMakeFiles/cleanfiles.dir/build.make CMakeFiles/cleanfiles.dir/filesplit.cpp.o
.PHONY : filesplit.cpp.o

filesplit.i: filesplit.cpp.i

.PHONY : filesplit.i

# target to preprocess a source file
filesplit.cpp.i:
	$(MAKE) -f CMakeFiles/cleanfiles.dir/build.make CMakeFiles/cleanfiles.dir/filesplit.cpp.i
.PHONY : filesplit.cpp.i

filesplit.s: filesplit.cpp.s

.PHONY : filesplit.s

# target to generate assembly for a file
filesplit.cpp.s:
	$(MAKE) -f CMakeFiles/cleanfiles.dir/build.make CMakeFiles/cleanfiles.dir/filesplit.cpp.s
.PHONY : filesplit.cpp.s

mda_cartpend.o: mda_cartpend.cpp.o

.PHONY : mda_cartpend.o

# target to build an object file
mda_cartpend.cpp.o:
	$(MAKE) -f CMakeFiles/mda_cartpend.dir/build.make CMakeFiles/mda_cartpend.dir/mda_cartpend.cpp.o
.PHONY : mda_cartpend.cpp.o

mda_cartpend.i: mda_cartpend.cpp.i

.PHONY : mda_cartpend.i

# target to preprocess a source file
mda_cartpend.cpp.i:
	$(MAKE) -f CMakeFiles/mda_cartpend.dir/build.make CMakeFiles/mda_cartpend.dir/mda_cartpend.cpp.i
.PHONY : mda_cartpend.cpp.i

mda_cartpend.s: mda_cartpend.cpp.s

.PHONY : mda_cartpend.s

# target to generate assembly for a file
mda_cartpend.cpp.s:
	$(MAKE) -f CMakeFiles/mda_cartpend.dir/build.make CMakeFiles/mda_cartpend.dir/mda_cartpend.cpp.s
.PHONY : mda_cartpend.cpp.s

mig_mda_cartpend.o: mig_mda_cartpend.cpp.o

.PHONY : mig_mda_cartpend.o

# target to build an object file
mig_mda_cartpend.cpp.o:
	$(MAKE) -f CMakeFiles/mig_mda_cartpend.dir/build.make CMakeFiles/mig_mda_cartpend.dir/mig_mda_cartpend.cpp.o
.PHONY : mig_mda_cartpend.cpp.o

mig_mda_cartpend.i: mig_mda_cartpend.cpp.i

.PHONY : mig_mda_cartpend.i

# target to preprocess a source file
mig_mda_cartpend.cpp.i:
	$(MAKE) -f CMakeFiles/mig_mda_cartpend.dir/build.make CMakeFiles/mig_mda_cartpend.dir/mig_mda_cartpend.cpp.i
.PHONY : mig_mda_cartpend.cpp.i

mig_mda_cartpend.s: mig_mda_cartpend.cpp.s

.PHONY : mig_mda_cartpend.s

# target to generate assembly for a file
mig_mda_cartpend.cpp.s:
	$(MAKE) -f CMakeFiles/mig_mda_cartpend.dir/build.make CMakeFiles/mig_mda_cartpend.dir/mig_mda_cartpend.cpp.s
.PHONY : mig_mda_cartpend.cpp.s

sac_cartpend.o: sac_cartpend.cpp.o

.PHONY : sac_cartpend.o

# target to build an object file
sac_cartpend.cpp.o:
	$(MAKE) -f CMakeFiles/sac_cartpend.dir/build.make CMakeFiles/sac_cartpend.dir/sac_cartpend.cpp.o
.PHONY : sac_cartpend.cpp.o

sac_cartpend.i: sac_cartpend.cpp.i

.PHONY : sac_cartpend.i

# target to preprocess a source file
sac_cartpend.cpp.i:
	$(MAKE) -f CMakeFiles/sac_cartpend.dir/build.make CMakeFiles/sac_cartpend.dir/sac_cartpend.cpp.i
.PHONY : sac_cartpend.cpp.i

sac_cartpend.s: sac_cartpend.cpp.s

.PHONY : sac_cartpend.s

# target to generate assembly for a file
sac_cartpend.cpp.s:
	$(MAKE) -f CMakeFiles/sac_cartpend.dir/build.make CMakeFiles/sac_cartpend.dir/sac_cartpend.cpp.s
.PHONY : sac_cartpend.cpp.s

sac_doubleint.o: sac_doubleint.cpp.o

.PHONY : sac_doubleint.o

# target to build an object file
sac_doubleint.cpp.o:
	$(MAKE) -f CMakeFiles/sac_doubleint.dir/build.make CMakeFiles/sac_doubleint.dir/sac_doubleint.cpp.o
.PHONY : sac_doubleint.cpp.o

sac_doubleint.i: sac_doubleint.cpp.i

.PHONY : sac_doubleint.i

# target to preprocess a source file
sac_doubleint.cpp.i:
	$(MAKE) -f CMakeFiles/sac_doubleint.dir/build.make CMakeFiles/sac_doubleint.dir/sac_doubleint.cpp.i
.PHONY : sac_doubleint.cpp.i

sac_doubleint.s: sac_doubleint.cpp.s

.PHONY : sac_doubleint.s

# target to generate assembly for a file
sac_doubleint.cpp.s:
	$(MAKE) -f CMakeFiles/sac_doubleint.dir/build.make CMakeFiles/sac_doubleint.dir/sac_doubleint.cpp.s
.PHONY : sac_doubleint.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... dklmda_di_image"
	@echo "... rebuild_cache"
	@echo "... edgedetect"
	@echo "... ergsac_cartpend"
	@echo "... cleanfiles"
	@echo "... mda_cartpend"
	@echo "... sac_doubleint"
	@echo "... ergsac_mda"
	@echo "... sac_cartpend"
	@echo "... mig_mda_cartpend"
	@echo "... dklsac_di_image"
	@echo "... ergsac_doubleint"
	@echo "... ergsac_dilincoln"
	@echo "... dklmda_si_image"
	@echo "... dklsac_doubleint"
	@echo "... dklmda_di_image.o"
	@echo "... dklmda_di_image.i"
	@echo "... dklmda_di_image.s"
	@echo "... dklmda_si_image.o"
	@echo "... dklmda_si_image.i"
	@echo "... dklmda_si_image.s"
	@echo "... dklsac_di_image.o"
	@echo "... dklsac_di_image.i"
	@echo "... dklsac_di_image.s"
	@echo "... dklsac_doubleint.o"
	@echo "... dklsac_doubleint.i"
	@echo "... dklsac_doubleint.s"
	@echo "... edgedetect.o"
	@echo "... edgedetect.i"
	@echo "... edgedetect.s"
	@echo "... ergsac_cartpend.o"
	@echo "... ergsac_cartpend.i"
	@echo "... ergsac_cartpend.s"
	@echo "... ergsac_dilincoln.o"
	@echo "... ergsac_dilincoln.i"
	@echo "... ergsac_dilincoln.s"
	@echo "... ergsac_doubleint.o"
	@echo "... ergsac_doubleint.i"
	@echo "... ergsac_doubleint.s"
	@echo "... ergsac_mda.o"
	@echo "... ergsac_mda.i"
	@echo "... ergsac_mda.s"
	@echo "... filesplit.o"
	@echo "... filesplit.i"
	@echo "... filesplit.s"
	@echo "... mda_cartpend.o"
	@echo "... mda_cartpend.i"
	@echo "... mda_cartpend.s"
	@echo "... mig_mda_cartpend.o"
	@echo "... mig_mda_cartpend.i"
	@echo "... mig_mda_cartpend.s"
	@echo "... sac_cartpend.o"
	@echo "... sac_cartpend.i"
	@echo "... sac_cartpend.s"
	@echo "... sac_doubleint.o"
	@echo "... sac_doubleint.i"
	@echo "... sac_doubleint.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

