# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kt-fitz/human-ergodicObj

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kt-fitz/human-ergodicObj

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kt-fitz/human-ergodicObj/CMakeFiles /home/kt-fitz/human-ergodicObj/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kt-fitz/human-ergodicObj/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ergsac_doubleint

# Build rule for target.
ergsac_doubleint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ergsac_doubleint
.PHONY : ergsac_doubleint

# fast build rule for target.
ergsac_doubleint/fast:
	$(MAKE) -f CMakeFiles/ergsac_doubleint.dir/build.make CMakeFiles/ergsac_doubleint.dir/build
.PHONY : ergsac_doubleint/fast

#=============================================================================
# Target rules for targets named ergsac_dilincoln

# Build rule for target.
ergsac_dilincoln: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ergsac_dilincoln
.PHONY : ergsac_dilincoln

# fast build rule for target.
ergsac_dilincoln/fast:
	$(MAKE) -f CMakeFiles/ergsac_dilincoln.dir/build.make CMakeFiles/ergsac_dilincoln.dir/build
.PHONY : ergsac_dilincoln/fast

#=============================================================================
# Target rules for targets named ergsac_digauss

# Build rule for target.
ergsac_digauss: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ergsac_digauss
.PHONY : ergsac_digauss

# fast build rule for target.
ergsac_digauss/fast:
	$(MAKE) -f CMakeFiles/ergsac_digauss.dir/build.make CMakeFiles/ergsac_digauss.dir/build
.PHONY : ergsac_digauss/fast

ergsac_digauss.o: ergsac_digauss.cpp.o

.PHONY : ergsac_digauss.o

# target to build an object file
ergsac_digauss.cpp.o:
	$(MAKE) -f CMakeFiles/ergsac_digauss.dir/build.make CMakeFiles/ergsac_digauss.dir/ergsac_digauss.cpp.o
.PHONY : ergsac_digauss.cpp.o

ergsac_digauss.i: ergsac_digauss.cpp.i

.PHONY : ergsac_digauss.i

# target to preprocess a source file
ergsac_digauss.cpp.i:
	$(MAKE) -f CMakeFiles/ergsac_digauss.dir/build.make CMakeFiles/ergsac_digauss.dir/ergsac_digauss.cpp.i
.PHONY : ergsac_digauss.cpp.i

ergsac_digauss.s: ergsac_digauss.cpp.s

.PHONY : ergsac_digauss.s

# target to generate assembly for a file
ergsac_digauss.cpp.s:
	$(MAKE) -f CMakeFiles/ergsac_digauss.dir/build.make CMakeFiles/ergsac_digauss.dir/ergsac_digauss.cpp.s
.PHONY : ergsac_digauss.cpp.s

ergsac_dilincoln.o: ergsac_dilincoln.cpp.o

.PHONY : ergsac_dilincoln.o

# target to build an object file
ergsac_dilincoln.cpp.o:
	$(MAKE) -f CMakeFiles/ergsac_dilincoln.dir/build.make CMakeFiles/ergsac_dilincoln.dir/ergsac_dilincoln.cpp.o
.PHONY : ergsac_dilincoln.cpp.o

ergsac_dilincoln.i: ergsac_dilincoln.cpp.i

.PHONY : ergsac_dilincoln.i

# target to preprocess a source file
ergsac_dilincoln.cpp.i:
	$(MAKE) -f CMakeFiles/ergsac_dilincoln.dir/build.make CMakeFiles/ergsac_dilincoln.dir/ergsac_dilincoln.cpp.i
.PHONY : ergsac_dilincoln.cpp.i

ergsac_dilincoln.s: ergsac_dilincoln.cpp.s

.PHONY : ergsac_dilincoln.s

# target to generate assembly for a file
ergsac_dilincoln.cpp.s:
	$(MAKE) -f CMakeFiles/ergsac_dilincoln.dir/build.make CMakeFiles/ergsac_dilincoln.dir/ergsac_dilincoln.cpp.s
.PHONY : ergsac_dilincoln.cpp.s

ergsac_doubleint.o: ergsac_doubleint.cpp.o

.PHONY : ergsac_doubleint.o

# target to build an object file
ergsac_doubleint.cpp.o:
	$(MAKE) -f CMakeFiles/ergsac_doubleint.dir/build.make CMakeFiles/ergsac_doubleint.dir/ergsac_doubleint.cpp.o
.PHONY : ergsac_doubleint.cpp.o

ergsac_doubleint.i: ergsac_doubleint.cpp.i

.PHONY : ergsac_doubleint.i

# target to preprocess a source file
ergsac_doubleint.cpp.i:
	$(MAKE) -f CMakeFiles/ergsac_doubleint.dir/build.make CMakeFiles/ergsac_doubleint.dir/ergsac_doubleint.cpp.i
.PHONY : ergsac_doubleint.cpp.i

ergsac_doubleint.s: ergsac_doubleint.cpp.s

.PHONY : ergsac_doubleint.s

# target to generate assembly for a file
ergsac_doubleint.cpp.s:
	$(MAKE) -f CMakeFiles/ergsac_doubleint.dir/build.make CMakeFiles/ergsac_doubleint.dir/ergsac_doubleint.cpp.s
.PHONY : ergsac_doubleint.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ergsac_doubleint"
	@echo "... ergsac_dilincoln"
	@echo "... rebuild_cache"
	@echo "... ergsac_digauss"
	@echo "... ergsac_digauss.o"
	@echo "... ergsac_digauss.i"
	@echo "... ergsac_digauss.s"
	@echo "... ergsac_dilincoln.o"
	@echo "... ergsac_dilincoln.i"
	@echo "... ergsac_dilincoln.s"
	@echo "... ergsac_doubleint.o"
	@echo "... ergsac_doubleint.i"
	@echo "... ergsac_doubleint.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

